[package]
name = "rust64"
version = "0.6.0"
authors = [ "Krzysztof Kondrak <krzysztof.kondrak@gmail.com>" ]

[dependencies]
sdl2 = "0.15.0"
minifb = "0.10"
rand = "0.3.14"
time = "0.1.34"
byteorder = "1.2.2"
enum_primitive = "0.1"
num = "0.1"
